### ISSUE TITLE
Help with SSL mapping

### ISSUE THREAD

**Issue by apeloquin-agilysys** [confluentinc/confluent-kafka-javascript#46]
Since SSL mapping is not provided as part of the KafkaJS config migration, I have a question on how to migrate a KafkaJS SSL configuration.  

We have 3rd party SSL-based connections that are configured today in KafkaJS as such:
```yml
brokers:
  - kafka-dev1.some-domain.local:9096
ssl:
  ca: ${secret.kafka.ca}
  key: ${secret.kafka.key}
  cert: ${secret.kafka.cert}
  passphrase: ${secret.kafka.passphrase}
  checkServerIdentity: false  # disables hostname verification
```
...where `${secret.kafka.ca}`, `${secret.kafka.key}`, and `${secret.kafka.cert}` are the string contents of .pem files (and the .pem files are not accessible at runtime).

I see a very wide range of ssl options in _GlobalConfig_, some prefixed with `ssl_` and others with `ssl.`

I'm not sure how I should be mapping these to incorporate the passphrase and _disable hostname verification_.
```
ssl_ca: ${secret.kafka.ca}
ssl_key: ${secret.kafka.key}
ssl_certificate: ${secret.kafka.cert}
???
```
-or-
```
ssl.ca.pem: ${secret.kafka.ca}
ssl.key.pem: ${secret.kafka.key}
ssl.key.password: ${secret.kafka.passphrase}
ssl.certificate.pem: ${secret.kafka.cert}
???
```
-or-
other?

Thanks!
